#!/usr/bin/env python3
"""Generate countries.json: Turkish name, aliases (English), flag image URL,
emoji fallback, IANA timezone — for the country picker."""
import json

def flag(code):
    """ISO 3166-1 alpha-2 -> emoji flag (regional indicators)."""
    return "".join(chr(0x1F1E6 + ord(c) - 0x41) for c in code)

def subflag(tag):
    """Black flag + tag sequence for UK home nations."""
    return "\U0001F3F4" + "".join(chr(0xE0000 + ord(c)) for c in tag) + "\U000E007F"

# (code, English name, IANA timezone)
COUNTRIES = [
    # ---- Africa ----
    ("DZ","Algeria","Africa/Algiers"),
    ("AO","Angola","Africa/Luanda"),
    ("BJ","Benin","Africa/Porto-Novo"),
    ("BW","Botswana","Africa/Gaborone"),
    ("BF","Burkina Faso","Africa/Ouagadougou"),
    ("BI","Burundi","Africa/Bujumbura"),
    ("CV","Cape Verde","Atlantic/Cape_Verde"),
    ("CM","Cameroon","Africa/Douala"),
    ("CF","Central African Republic","Africa/Bangui"),
    ("TD","Chad","Africa/Ndjamena"),
    ("KM","Comoros","Indian/Comoro"),
    ("CG","Republic of the Congo","Africa/Brazzaville"),
    ("CD","Democratic Republic of the Congo","Africa/Kinshasa"),
    ("CI","Côte d'Ivoire","Africa/Abidjan"),
    ("DJ","Djibouti","Africa/Djibouti"),
    ("EG","Egypt","Africa/Cairo"),
    ("GQ","Equatorial Guinea","Africa/Malabo"),
    ("ER","Eritrea","Africa/Asmara"),
    ("SZ","Eswatini","Africa/Mbabane"),
    ("ET","Ethiopia","Africa/Addis_Ababa"),
    ("GA","Gabon","Africa/Libreville"),
    ("GM","Gambia","Africa/Banjul"),
    ("GH","Ghana","Africa/Accra"),
    ("GN","Guinea","Africa/Conakry"),
    ("GW","Guinea-Bissau","Africa/Bissau"),
    ("KE","Kenya","Africa/Nairobi"),
    ("LS","Lesotho","Africa/Maseru"),
    ("LR","Liberia","Africa/Monrovia"),
    ("LY","Libya","Africa/Tripoli"),
    ("MG","Madagascar","Indian/Antananarivo"),
    ("MW","Malawi","Africa/Blantyre"),
    ("ML","Mali","Africa/Bamako"),
    ("MR","Mauritania","Africa/Nouakchott"),
    ("MU","Mauritius","Indian/Mauritius"),
    ("MA","Morocco","Africa/Casablanca"),
    ("MZ","Mozambique","Africa/Maputo"),
    ("NA","Namibia","Africa/Windhoek"),
    ("NE","Niger","Africa/Niamey"),
    ("NG","Nigeria","Africa/Lagos"),
    ("RW","Rwanda","Africa/Kigali"),
    ("ST","São Tomé and Príncipe","Africa/Sao_Tome"),
    ("SN","Senegal","Africa/Dakar"),
    ("SC","Seychelles","Indian/Mahe"),
    ("SL","Sierra Leone","Africa/Freetown"),
    ("SO","Somalia","Africa/Mogadishu"),
    ("ZA","South Africa","Africa/Johannesburg"),
    ("SS","South Sudan","Africa/Juba"),
    ("SD","Sudan","Africa/Khartoum"),
    ("TZ","Tanzania","Africa/Dar_es_Salaam"),
    ("TG","Togo","Africa/Lome"),
    ("TN","Tunisia","Africa/Tunis"),
    ("UG","Uganda","Africa/Kampala"),
    ("ZM","Zambia","Africa/Lusaka"),
    ("ZW","Zimbabwe","Africa/Harare"),
    ("EH","Western Sahara","Africa/El_Aaiun"),
    ("YT","Mayotte","Indian/Mayotte"),
    ("RE","Réunion","Indian/Reunion"),
    ("SH","Saint Helena","Atlantic/St_Helena"),
    # ---- Americas ----
    ("AG","Antigua and Barbuda","America/Antigua"),
    ("AI","Anguilla","America/Anguilla"),
    ("AR","Argentina","America/Argentina/Buenos_Aires"),
    ("AW","Aruba","America/Aruba"),
    ("BS","Bahamas","America/Nassau"),
    ("BB","Barbados","America/Barbados"),
    ("BZ","Belize","America/Belize"),
    ("BM","Bermuda","Atlantic/Bermuda"),
    ("BQ","Caribbean Netherlands","America/Kralendijk"),
    ("BO","Bolivia","America/La_Paz"),
    ("BR","Brazil","America/Sao_Paulo"),
    ("VG","British Virgin Islands","America/Tortola"),
    ("CA","Canada","America/Toronto"),
    ("KY","Cayman Islands","America/Cayman"),
    ("CL","Chile","America/Santiago"),
    ("CO","Colombia","America/Bogota"),
    ("CR","Costa Rica","America/Costa_Rica"),
    ("CU","Cuba","America/Havana"),
    ("CW","Curaçao","America/Curacao"),
    ("DM","Dominica","America/Dominica"),
    ("DO","Dominican Republic","America/Santo_Domingo"),
    ("EC","Ecuador","America/Guayaquil"),
    ("SV","El Salvador","America/El_Salvador"),
    ("FK","Falkland Islands","Atlantic/Stanley"),
    ("GF","French Guiana","America/Cayenne"),
    ("GL","Greenland","America/Nuuk"),
    ("GD","Grenada","America/Grenada"),
    ("GP","Guadeloupe","America/Guadeloupe"),
    ("GT","Guatemala","America/Guatemala"),
    ("GY","Guyana","America/Guyana"),
    ("HT","Haiti","America/Port-au-Prince"),
    ("HN","Honduras","America/Tegucigalpa"),
    ("JM","Jamaica","America/Jamaica"),
    ("MQ","Martinique","America/Martinique"),
    ("MX","Mexico","America/Mexico_City"),
    ("MS","Montserrat","America/Montserrat"),
    ("NI","Nicaragua","America/Managua"),
    ("PA","Panama","America/Panama"),
    ("PY","Paraguay","America/Asuncion"),
    ("PE","Peru","America/Lima"),
    ("PR","Puerto Rico","America/Puerto_Rico"),
    ("KN","Saint Kitts and Nevis","America/St_Kitts"),
    ("LC","Saint Lucia","America/St_Lucia"),
    ("MF","Saint Martin","America/Marigot"),
    ("PM","Saint Pierre and Miquelon","America/Miquelon"),
    ("VC","Saint Vincent and the Grenadines","America/St_Vincent"),
    ("SX","Sint Maarten","America/Lower_Princes"),
    ("BL","Saint Barthélemy","America/St_Barthelemy"),
    ("SR","Suriname","America/Paramaribo"),
    ("TT","Trinidad and Tobago","America/Port_of_Spain"),
    ("TC","Turks and Caicos Islands","America/Grand_Turk"),
    ("US","United States","America/New_York"),
    ("VI","U.S. Virgin Islands","America/St_Thomas"),
    ("UY","Uruguay","America/Montevideo"),
    ("VE","Venezuela","America/Caracas"),
    # ---- Asia ----
    ("AF","Afghanistan","Asia/Kabul"),
    ("AM","Armenia","Asia/Yerevan"),
    ("AZ","Azerbaijan","Asia/Baku"),
    ("BH","Bahrain","Asia/Bahrain"),
    ("BD","Bangladesh","Asia/Dhaka"),
    ("BT","Bhutan","Asia/Thimphu"),
    ("BN","Brunei","Asia/Brunei"),
    ("KH","Cambodia","Asia/Phnom_Penh"),
    ("CN","China","Asia/Shanghai"),
    ("CY","Cyprus","Asia/Nicosia"),
    ("GE","Georgia","Asia/Tbilisi"),
    ("HK","Hong Kong","Asia/Hong_Kong"),
    ("IN","India","Asia/Kolkata"),
    ("ID","Indonesia","Asia/Jakarta"),
    ("IR","Iran","Asia/Tehran"),
    ("IQ","Iraq","Asia/Baghdad"),
    ("IL","Israel","Asia/Jerusalem"),
    ("JP","Japan","Asia/Tokyo"),
    ("JO","Jordan","Asia/Amman"),
    ("KZ","Kazakhstan","Asia/Almaty"),
    ("KW","Kuwait","Asia/Kuwait"),
    ("KG","Kyrgyzstan","Asia/Bishkek"),
    ("LA","Laos","Asia/Vientiane"),
    ("LB","Lebanon","Asia/Beirut"),
    ("MO","Macau","Asia/Macau"),
    ("MY","Malaysia","Asia/Kuala_Lumpur"),
    ("MV","Maldives","Indian/Maldives"),
    ("MN","Mongolia","Asia/Ulaanbaatar"),
    ("MM","Myanmar","Asia/Yangon"),
    ("NP","Nepal","Asia/Kathmandu"),
    ("KP","North Korea","Asia/Pyongyang"),
    ("OM","Oman","Asia/Muscat"),
    ("PK","Pakistan","Asia/Karachi"),
    ("PS","Palestine","Asia/Gaza"),
    ("PH","Philippines","Asia/Manila"),
    ("QA","Qatar","Asia/Qatar"),
    ("SA","Saudi Arabia","Asia/Riyadh"),
    ("SG","Singapore","Asia/Singapore"),
    ("KR","South Korea","Asia/Seoul"),
    ("LK","Sri Lanka","Asia/Colombo"),
    ("SY","Syria","Asia/Damascus"),
    ("TW","Taiwan","Asia/Taipei"),
    ("TJ","Tajikistan","Asia/Dushanbe"),
    ("TH","Thailand","Asia/Bangkok"),
    ("TL","Timor-Leste","Asia/Dili"),
    ("TR","Turkey","Europe/Istanbul"),
    ("TM","Turkmenistan","Asia/Ashgabat"),
    ("AE","United Arab Emirates","Asia/Dubai"),
    ("UZ","Uzbekistan","Asia/Tashkent"),
    ("VN","Vietnam","Asia/Ho_Chi_Minh"),
    ("YE","Yemen","Asia/Aden"),
    ("XK","Kosovo","Europe/Belgrade"),
    # ---- Europe ----
    ("AL","Albania","Europe/Tirane"),
    ("AD","Andorra","Europe/Andorra"),
    ("AT","Austria","Europe/Vienna"),
    ("BY","Belarus","Europe/Minsk"),
    ("BE","Belgium","Europe/Brussels"),
    ("BA","Bosnia and Herzegovina","Europe/Sarajevo"),
    ("BG","Bulgaria","Europe/Sofia"),
    ("HR","Croatia","Europe/Zagreb"),
    ("CZ","Czechia","Europe/Prague"),
    ("DK","Denmark","Europe/Copenhagen"),
    ("EE","Estonia","Europe/Tallinn"),
    ("FO","Faroe Islands","Atlantic/Faroe"),
    ("FI","Finland","Europe/Helsinki"),
    ("FR","France","Europe/Paris"),
    ("DE","Germany","Europe/Berlin"),
    ("GI","Gibraltar","Europe/Gibraltar"),
    ("GR","Greece","Europe/Athens"),
    ("GG","Guernsey","Europe/Guernsey"),
    ("HU","Hungary","Europe/Budapest"),
    ("IS","Iceland","Atlantic/Reykjavik"),
    ("IE","Ireland","Europe/Dublin"),
    ("IM","Isle of Man","Europe/Isle_of_Man"),
    ("IT","Italy","Europe/Rome"),
    ("JE","Jersey","Europe/Jersey"),
    ("LV","Latvia","Europe/Riga"),
    ("LI","Liechtenstein","Europe/Vaduz"),
    ("LT","Lithuania","Europe/Vilnius"),
    ("LU","Luxembourg","Europe/Luxembourg"),
    ("MT","Malta","Europe/Malta"),
    ("MD","Moldova","Europe/Chisinau"),
    ("MC","Monaco","Europe/Monaco"),
    ("ME","Montenegro","Europe/Podgorica"),
    ("NL","Netherlands","Europe/Amsterdam"),
    ("MK","North Macedonia","Europe/Skopje"),
    ("NO","Norway","Europe/Oslo"),
    ("PL","Poland","Europe/Warsaw"),
    ("PT","Portugal","Europe/Lisbon"),
    ("RO","Romania","Europe/Bucharest"),
    ("RU","Russia","Europe/Moscow"),
    ("SM","San Marino","Europe/San_Marino"),
    ("RS","Serbia","Europe/Belgrade"),
    ("SK","Slovakia","Europe/Bratislava"),
    ("SI","Slovenia","Europe/Ljubljana"),
    ("ES","Spain","Europe/Madrid"),
    ("SE","Sweden","Europe/Stockholm"),
    ("CH","Switzerland","Europe/Zurich"),
    ("UA","Ukraine","Europe/Kyiv"),
    ("GB","United Kingdom","Europe/London"),
    ("VA","Vatican City","Europe/Vatican"),
    ("AX","Åland Islands","Europe/Mariehamn"),
    # ---- Oceania ----
    ("AS","American Samoa","Pacific/Pago_Pago"),
    ("AU","Australia","Australia/Sydney"),
    ("CC","Cocos (Keeling) Islands","Indian/Cocos"),
    ("CK","Cook Islands","Pacific/Rarotonga"),
    ("CX","Christmas Island","Indian/Christmas"),
    ("FJ","Fiji","Pacific/Fiji"),
    ("PF","French Polynesia","Pacific/Tahiti"),
    ("GU","Guam","Pacific/Guam"),
    ("HM","Heard Island and McDonald Islands","Indian/Kerguelen"),
    ("KI","Kiribati","Pacific/Tarawa"),
    ("MH","Marshall Islands","Pacific/Majuro"),
    ("FM","Micronesia","Pacific/Chuuk"),
    ("NR","Nauru","Pacific/Nauru"),
    ("NC","New Caledonia","Pacific/Noumea"),
    ("NZ","New Zealand","Pacific/Auckland"),
    ("NU","Niue","Pacific/Niue"),
    ("NF","Norfolk Island","Pacific/Norfolk"),
    ("MP","Northern Mariana Islands","Pacific/Saipan"),
    ("PW","Palau","Pacific/Palau"),
    ("PG","Papua New Guinea","Pacific/Port_Moresby"),
    ("PN","Pitcairn Islands","Pacific/Pitcairn"),
    ("WS","Samoa","Pacific/Apia"),
    ("SB","Solomon Islands","Pacific/Guadalcanal"),
    ("GS","South Georgia and the South Sandwich Islands","Atlantic/South_Georgia"),
    ("TK","Tokelau","Pacific/Fakaofo"),
    ("TO","Tonga","Pacific/Tongatapu"),
    ("TV","Tuvalu","Pacific/Funafuti"),
    ("VU","Vanuatu","Pacific/Efate"),
    ("WF","Wallis and Futuna","Pacific/Wallis"),
    ("AQ","Antarctica","Antarctica/Troll"),
]

# Extra aliases beyond the English name (useful for searching)
EXTRA_ALIASES = {
    "US": ["USA", "America", "United States of America"],
    "GB": ["UK", "Britain", "Great Britain"],
    "TR": [],
    "AE": ["UAE"],
    "CD": ["DR Congo", "Congo"],
    "CZ": ["Czech Republic"],
    "NL": ["Holland", "Netherlands"],
    "VA": ["Holy See", "Vatican"],
    "MK": ["Macedonia"],
    "MM": ["Burma"],
    "CI": ["Ivory Coast"],
    "CV": ["Cabo Verde"],
    "TL": ["East Timor"],
    "SZ": ["Swaziland"],
    "KR": ["Korea"],
    "KP": ["North Korea"],
    "RU": ["Russian Federation"],
    "PS": ["State of Palestine"],
}

# UK home nations + partially recognised states (extra entries)
EXTRAS = [
    {"code":"GB-ENG","name":"England","aliases":[],"flag":subflag("gbeng"),"img":"gb-eng","tz":"Europe/London"},
    {"code":"GB-SCT","name":"Scotland","aliases":[],"flag":subflag("gbsct"),"img":"gb-sct","tz":"Europe/London"},
    {"code":"GB-WLS","name":"Wales","aliases":[],"flag":subflag("gbwls"),"img":"gb-wls","tz":"Europe/London"},
    {"code":"GB-NIR","name":"Northern Ireland","aliases":[],"flag":flag("GB"),"img":"gb-nir","tz":"Europe/London"},
    {"code":"XAB","name":"Abkhazia","aliases":[],"flag":"\U0001F3F3\uFE0F","img":"https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_Abkhazia.svg?width=40","tz":"Europe/Moscow"},
    {"code":"XSO","name":"South Ossetia","aliases":[],"flag":"\U0001F3F3\uFE0F","img":"https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_South_Ossetia.svg?width=40","tz":"Europe/Moscow"},
]

out = []
for code, en, tz in COUNTRIES:
    name = en
    aliases = [en] + EXTRA_ALIASES.get(code, [])
    if code == "TR":
        # Turkey officially renamed itself "Türkiye" in English (2022).
        # Display "Turkiye" (ASCII); typing "Turkey" (or "Turkiye") selects it.
        name = "Turkiye"
        aliases = ["Turkey", "Türkiye"]
    # flagcdn path (lowercase alpha-2)
    path = code.lower()
    img = "https://flagcdn.com/w40/%s.png" % path
    out.append({
        "code": code,
        "name": name,
        "aliases": aliases,
        "flag": flag(code),
        "img": img,
        "tz": tz,
    })

for e in EXTRAS:
    out.append({
        "code": e["code"],
        "name": e["name"],
        "aliases": e["aliases"],
        "flag": e["flag"],
        "img": e["img"] if e["img"].startswith("http") else "https://flagcdn.com/w40/%s.png" % e["img"],
        "tz": e["tz"],
    })

# dedupe by code
seen = set()
final = []
for c in out:
    if c["code"] in seen:
        continue
    seen.add(c["code"])
    final.append(c)

final.sort(key=lambda x: x["name"].lower())

with open("countries.json", "w", encoding="utf-8") as f:
    json.dump(final, f, ensure_ascii=False, indent=1)

print("total:", len(final))
